### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by brandoncc** [petekinnecom/test_launcher#2]
Do you have any plans to support Rails 5 test commands? I would love to use this tool everywhere, but it doesn't work in Rails 5 projects with minitest because they need to be executed with the `rails` binary.

**Comment by petekinnecom** [comment]
Hi, thanks for asking!  I just tried generating a rails 5 application and scaffolding a model.  Using that application, it looked like things were working alright.  Do you have an example project I could see where things aren't working?  Or what kind of behavior are you seeing?

That being said, by default rails generates a scaffold that uses the Minispec style of tests, which I haven't added support for.  Maybe you're running into that?  Eg:

~~~ruby
require 'test_helper'

class StuffTest < ActiveSupport::TestCase
  # test "the truth" do
  #   assert true
  # end
end
~~~

I think that it does make sense to delegate the line number search to rails rather than my own, as it's probably handles metaprogrammed tests and other things a bit better.  But how to determine if we're in a rails 5 application, though?  Hmm... `bundle show` is probably a bit slow to tack on to the front of every test run.  I suppose it could be cached...  

I'll play around with it this week and see how it goes!

**Comment by petekinnecom** [comment]
I've been using test_launcher in multiple Rails >5 apps for a while now and haven't run into any issues. Maybe our test setups are different.  Are you still seeing problems...2 years later? 😂 😂

**Comment by brandoncc** [comment]
I don't even know where I was using this anymore 😂
