### ISSUE TITLE
Does it not work on windows?

### ISSUE THREAD

**Issue by stt106** [petekinnecom/test_launcher#3]
Does the VS code extension not work on windows?

**Comment by petekinnecom** [comment]
I'm not sure...

There's two parts to using it with vscode:
- The extension (https://marketplace.visualstudio.com/items?itemName=petekinnecom.terminal-command-keys)
- The gem (`gem install test_launcher`)

I would expect that the extension works on windows, since it just uses vscode's built in terminal API. 

I would expect that the gem probably does not. It's quite likely that it makes some assumption about having a unix-ish filesystem underneath it.  Maybe it would work with cygwin?  Not sure. I don't have a windows environment to test this on.

Have you tried installing the gem and trying a command or two?

**Comment by stt106** [comment]
I did install the gem but it still doesn't work.
In fact, I also tried on Linux and it just says test_launcher command can't be found despite having the gem installed.
Will try on macOS to see whether it works.

**Comment by petekinnecom** [comment]
I've tested the gem on linux and it works there, so I'm guessing that something is going on with your shell and which ruby it's trying to use.  Some things to check on Linux:

- How did you install ruby? Did you use rvm, rbenv, chruby, or use your distribution's package manager?
- In a terminal outside of vscode, does this run successfully? `gem install test_launcher && test_launcher --help` 
- If it works in a non-vscode terminal, then it may be the case that the shell in vscode is not using the correct ruby.  Try a `ruby -v` in both a terminal inside of vscode and outside of vscode and make sure they are the same.  (If they are, maybe even do a `which ruby` in both places to be double sure).

**Comment by petekinnecom** [comment]
closing since I haven't heard anything for a while
